export interface LogoOption {
  id: number;
  name: string;
  category: "monogram" | "wordmark" | "crest" | "curves" | "iterations";
  desc: string;
  image: string;
  isFinalist?: boolean;
}

export const LOGO_OPTIONS: LogoOption[] = [
  { id: 1, name: "Geometric Monogram", category: "monogram", desc: "Monogram combining B, E, and ascending progress steps.", image: "/logos/option1.png" },
  { id: 2, name: "Luxury Wordmark", category: "wordmark", desc: "Modern geometric typography with sleek BE ligatures.", image: "/logos/option2.png" },
  { id: 3, name: "Biometric Crest", category: "crest", desc: "Data-backed double-helix and heart rate wave inside a shield.", image: "/logos/option3.png" },
  { id: 4, name: "Monogram: Sleek Negative Space", category: "monogram", desc: "Sharp negative-space ascending arrow cutting through B & E.", image: "/logos/option4.png" },
  { id: 5, name: "Wordmark: Bold Slash Cuts", category: "wordmark", desc: "Futuristic typography with slash-cut angles and rose ligatures.", image: "/logos/option5.png" },
  { id: 6, name: "Dominion Wing Crest", category: "crest", desc: "Abstract wing and crown lines for elite status.", image: "/logos/option6.png" },
  { id: 7, name: "Hourglass Silhouette", category: "curves", desc: "Line-art female hourglass curves transitioning into toned, athletic form.", image: "/logos/option7.png" },
  { id: 8, name: "Curved Monogram", category: "monogram", desc: "Initials B and E tracing feminine hips and waist contours.", image: "/logos/option8.png" },
  { id: 9, name: "Metamorphosis Butterfly", category: "crest", desc: "Blending a butterfly crest with flowing female curves.", image: "/logos/option9.png" },
  { id: 10, name: "Royal Palm & Pillar", category: "curves", desc: "Classical structural column merged with a single palm branch.", image: "/logos/option10.png" },
  { id: 11, name: "Boca Country Club Crest", category: "crest", desc: "Circular shield enclosing styled B & E and a gold palm accent.", image: "/logos/option11.png" },
  { id: 12, name: "Seaside Ocean Wave", category: "curves", desc: "Ocean wave curves merging with a toned female silhouette.", image: "/logos/option12.png" },
  { id: 13, name: "Lotus Crown", category: "crest", desc: "Geometric lotus flower morphing into a five-point crown.", image: "/logos/option13.png" },
  { id: 14, name: "Slash Interval Wordmark", category: "wordmark", desc: "Crossbars on E and A replaced by slanted rose-pink slashes.", image: "/logos/option14.png" },
  { id: 15, name: "Hourglass Ligature", category: "wordmark", desc: "Editorial serif style where O and D link via a waistline contour.", image: "/logos/option15.png" },
  { id: 16, name: "Biometric Wave Wordmark", category: "wordmark", desc: "Crossbar in H transitions to a heart rate pulse line.", image: "/logos/option16.png" },
  { id: 17, name: "Crown Dot Wordmark", category: "wordmark", desc: "Clean typeface with a micro gold crown as the dot on the 'I'.", image: "/logos/option17.png" },
  { id: 18, name: "Chiseled Iron & Gold", category: "wordmark", desc: "3D block text where one face is cast iron and the other is gold.", image: "/logos/option18.png" },
  { id: 19, name: "Knurled Barbell Accent", category: "wordmark", desc: "Letter I stylized as a barbell bar with a gold knurled pattern grip.", image: "/logos/option19.png" },
  { id: 20, name: "Sheared Steel & Rose Wire", category: "wordmark", desc: "Heavy steel plate lettering linked by an ultra-thin glowing rose wire.", image: "/logos/option20.png" },
  { id: 21, name: "Anvil Serif & Crown-Spire", category: "wordmark", desc: "Thick anvil-like serifs terminating in gold crown spires.", image: "/logos/option21.png" },
  { id: 22, name: "Clean Barbell Wordmark", category: "wordmark", desc: "Minimalist modern text where the letter I is a vertical barbell.", image: "/logos/option22.png" },
  { id: 23, name: "Kettlebell Monogram", category: "monogram", desc: "Clean kettlebell icon where curves form the initials B and E.", image: "/logos/option23.png" },
  { id: 24, name: "Clean Dumbbell Wordmark", category: "wordmark", desc: "Typography where the letter O is a modern hexagonal dumbbell.", image: "/logos/option24.png" },
  { id: 25, name: "Kettlebell & Peak Crest", category: "crest", desc: "Circular crest enclosing a kettlebell with a mountain peak inside.", image: "/logos/option25.png" },
  { id: 26, name: "Gymnastic Rings Icon", category: "monogram", desc: "Two interlocking rings hanging from straps that trace B and E.", image: "/logos/option26.png" },
  { id: 27, name: "Speed Jump Rope Ligature", category: "wordmark", desc: "Modern wordmark with a thin speed-rope cable looping below the text.", image: "/logos/option27.png" },
  { id: 28, name: "Olympic Weight Plate", category: "wordmark", desc: "Olympic barbell weight plate integrated as the letter O.", image: "/logos/option28.png" },
  { id: 29, name: "Resistance Loop Band", category: "wordmark", desc: "Modern typography where the word 'BY' is inside a loop band.", image: "/logos/option29.png" },
  { id: 30, name: "Iteration 18.1: Brushed Gold & Pitted Iron", category: "iterations", desc: "Option 18 3D block lettering with polished gold leaf face and dark pitted cast iron sides.", image: "/logos/option30.png" },
  { id: 31, name: "Iteration 18.2: Rose Gold & Charcoal Steel", category: "iterations", desc: "Option 18 beveled block lettering with brushed rose gold face and dark charcoal steel sides.", image: "/logos/option31.png" },
  { id: 32, name: "Iteration 18.3: Knurled Iron & Gold Inlay", category: "iterations", desc: "Option 18 knurled dark iron lettering with a thin polished gold inlay running through the center.", image: "/logos/option32.png" },
  { id: 33, name: "Iteration 18.4: Chamfered Gold & Cast Iron", category: "iterations", desc: "Option 18 block lettering with polished champagne gold face and deep chamfered dark cast iron sides.", image: "/logos/option33.png" },
  { id: 34, name: "Iteration 18.5: Gold Leaf & Chiseled Slate", category: "iterations", desc: "Option 18 block lettering with textured gold leaf face and raw chiseled black slate stone sides.", image: "/logos/option34.png" },
  { id: 35, name: "Iteration 18.6: Gold Face & Matte Black Steel", category: "iterations", desc: "Option 18 block lettering with mirror-polished gold face and smooth matte black steel sides.", image: "/logos/option35.png" },
  { id: 36, name: "Iteration 18.7: Diagonal Slice Split", category: "iterations", desc: "Option 18 block letters sliced diagonally, left side polished gold, right side dark iron.", image: "/logos/option36.png", isFinalist: true },
  { id: 37, name: "Iteration 18.8: Iron with Gold Channels", category: "iterations", desc: "Option 18 chiseled dark cast iron letters with deep center grooves filled with textured gold leaf.", image: "/logos/option37.png" },
  { id: 38, name: "Iteration 18.9: Tagline Integration", category: "iterations", desc: "Option 18 3D block lettering with the tagline 'fitness, strength, body recomposition, and nutrition coach' centered underneath in a clean flat font.", image: "/logos/option38.png" },
  { id: 39, name: "Iteration 18.10: Full Equipment & Tagline Integration", category: "iterations", desc: "Option 18 3D block lettering with the letter 'I' as a dumbbell, 'O' as a weight plate, and the tagline centered underneath in a clean flat font.", image: "/logos/option39.png" },
  { id: 40, name: "Iteration 7.1: Silhouette with Equipment & Tagline", category: "iterations", desc: "Option 7 hourglass line-art female silhouette holding a weight, with 'I' as dumbbell, 'O' as weight plate, and the tagline centered underneath.", image: "/logos/option40.png" },
  { id: 41, name: "Combo Master: Logo 5-7-18 Ultimate Combo", category: "iterations", desc: "Ultimate combined concept featuring 3D block wordmark (Option 18 face/Option 5 slashes), hourglass female silhouette holding a weight (Option 7), 'I' as dumbbell, 'O' as weight plate, and flat unchiseled tagline.", image: "/logos/option41.png" },
  { id: 42, name: "Combo 5-7-18: Silhouette & 3D Block Combo (High Contrast)", category: "iterations", desc: "Refined combination of Option 18's 3D block text, Option 7's line-art female holding a dumbbell, and Option 5's slash cuts. Left-side body lines are highlighted for maximum contrast on both black and white backgrounds.", image: "/logos/option42.png" },
  { id: 43, name: "Simplified Option 1: Minimalist Line Silhouette", category: "iterations", desc: "Ultra-simplified continuous-stroke female silhouette holding a dumbbell, integrated with bold flat modern 'BODIED BY ESH' typography. Striking, high-contrast, and clean.", image: "/logos/option43.png" },
  { id: 44, name: "Simplified Option 2: Negative Space BE Monogram", category: "iterations", desc: "A sleek, minimal monogram where the initials B and E enclose a stylized dumbbell and weight plate contour in the negative space. High versatility and modern punch.", image: "/logos/option44.png" },
  { id: 45, name: "Simplified Option 3: Faceted Torso Emblem", category: "iterations", desc: "Abstract geometric lines forming an athletic female silhouette, paired with elegant, clean minimalist sans-serif typography. Modern high-end luxury wellness branding.", image: "/logos/option45.png" },
  { id: 46, name: "Simplified Option 4: Continuous Line Athlete Badge", category: "iterations", desc: "Continuous line-art drawing of a female athlete holding a kettlebell inside an elegant thin circular border, paired with premium high-contrast typography.", image: "/logos/option46.png" },
  { id: 47, name: "Simplified Option 5: Circular Stencil Badge", category: "iterations", desc: "A bold, graphic fitness badge enclosing stencil initials B and E integrated with a minimal horizontal barbell. Clean, heavy weight, and highly iconic.", image: "/logos/option47.png" },
  { id: 48, name: "Simplified Option 6: Futuristic Wordmark", category: "iterations", desc: "A sleek, futuristic typographic wordmark for 'BODIED BY ESH' featuring bold custom angles and negative-space accents. Very modern and premium sports branding.", image: "/logos/option48.png" },
  { id: 49, name: "Simplified Option 7: Dumbbell Geometric Crest", category: "iterations", desc: "A minimalist geometric fitness emblem featuring a stylized dumbbell integrated with modern abstract lines inside a sleek, clean vector crest.", image: "/logos/option49.png" },
  { id: 50, name: "Simplified Option 8: Flat Equipment Wordmark", category: "iterations", desc: "An ultra-clean flat typographic wordmark where the letter 'I' is designed as a vertical barbell and 'O' is a weight plate. Bold, direct, and iconic.", image: "/logos/option50.png" },
  { id: 51, name: "Simplified Option 9: Track Monogram BE", category: "iterations", desc: "A sleek, athletic monogram combining the initials B and E built from bold, minimalist sports track lines and progress bars. High-end modern fitness emblem.", image: "/logos/option51.png" },
  { id: 52, name: "Simplified Option 10: Faceted Crown Emblem", category: "iterations", desc: "A premium, minimalist wellness logo featuring a single simplified crown made of sharp gold facets, placed above clean modern typography.", image: "/logos/option52.png" },
  { id: 53, name: "Feedback Option 1: Modern Serif Wordmark", category: "iterations", desc: "A bold, elegant modern serif wordmark incorporating a dumbbell as the letter 'I' and a flat weight plate as the 'O', complete with centered tagline below.", image: "/logos/option53.png" },
  { id: 54, name: "Feedback Option 2: Gold Outline Block Wordmark", category: "iterations", desc: "Modern typographic block lettering 'BODIED BY ESH' featuring a sleek gold outline, matte black fill, and centered unchiseled tagline.", image: "/logos/option54.png" },
  { id: 55, name: "Feedback Option 3: Continuous Line BE Monogram", category: "iterations", desc: "A minimalist sports monogram where the letters B and E are drawn with a single continuous thin gold line wrapping around a central dumbbell.", image: "/logos/option55.png" },
  { id: 56, name: "Feedback Option 4: Silver/Black 3D Block", category: "iterations", desc: "A premium 3D block wordmark using polished silver face and dark matte steel sides, featuring a barbell 'I', weight plate 'O', and tagline.", image: "/logos/option56.png" },
  { id: 57, name: "Feedback Option 5: Barbell Divider Wordmark", category: "iterations", desc: "Minimalist layout with 'BODIED' and 'BY ESH' in a clean sans-serif typeface separated horizontally by a thin gold barbell divider line.", image: "/logos/option57.png" },
  { id: 58, name: "Feedback Option 6: Editorial Equipment Wordmark", category: "iterations", desc: "Chic modern editorial typographic logo featuring a gold weight plate for the 'O' in 'BODIED' and a line-art barbell for the 'I' in 'BY ESH'.", image: "/logos/option58.png" },
  { id: 59, name: "Feedback Option 7: Dumbbell Stencil Crest", category: "iterations", desc: "Minimalist athletic shield crest enclosing bold stencil BE initials with a small clean dumbbell shape sitting at the bottom base.", image: "/logos/option59.png" },
  { id: 60, name: "Feedback Option 8: Dual Dumbbell H Wordmark", category: "iterations", desc: "A clever typographic design where the final letter 'H' in 'BODIED BY ESH' is constructed from two vertical dumbbells side-by-side.", image: "/logos/option60.png" },
  { id: 61, name: "Feedback Option 9: Chamfered Gold Wordmark", category: "iterations", desc: "Typographic wordmark with custom chamfered corners in brushed gold, containing a dumbbell 'I', weight plate 'O', and unchiseled tagline.", image: "/logos/option61.png" },
  { id: 62, name: "Feedback Option 10: Central BE Weight Plate", category: "iterations", desc: "Sleek circular emblem enclosing a dark weight plate icon with clean gold initials 'BE' placed in the center hole.", image: "/logos/option62.png" },
  { id: 63, name: "Iteration 36A: Rose Gold & White Ceramic Split", category: "iterations", desc: "Diagonal Slice Split — Sleek rose gold face combined with modern matte white ceramic details.", image: "/logos/option63.png" },
  { id: 64, name: "Iteration 36B: Brushed Platinum & Black Steel Split", category: "iterations", desc: "Diagonal Slice Split — High-performance brushed platinum matched with matte black steel.", image: "/logos/option64.png" },
  { id: 65, name: "Iteration 36C: Polished Gold & Charcoal Slate Split", category: "iterations", desc: "Diagonal Slice Split — Polished gold face contrasted with deep-textured charcoal slate stone.", image: "/logos/option65.png" },
  { id: 66, name: "Iteration 39A: Gold Leaf & Chiseled Slate Wordmark", category: "iterations", desc: "Full Equipment & Tagline — Textured gold leaf front faces on chiseled black slate stone letter sides.", image: "/logos/option66.png" },
  { id: 67, name: "Iteration 39B: Pure Mirror-Polished Gold Wordmark", category: "iterations", desc: "Full Equipment & Tagline — Mirror-polished premium gold applied to all lettering surfaces.", image: "/logos/option67.png" },
  { id: 68, name: "Iteration 39C: Silver & Charcoal Steel Wordmark", category: "iterations", desc: "Full Equipment & Tagline — Polished silver chrome faces with matte black carbon steel letter sides.", image: "/logos/option68.png" },
  { id: 69, name: "Iteration 61A: Chamfered Gold Outline Wordmark", category: "iterations", desc: "Chamfered Gold Wordmark — Stencil-like outline style with a clean inline hollow cut.", image: "/logos/option69.png" },
  { id: 70, name: "Iteration 61B: Chamfered Brushed Rose Gold Wordmark", category: "iterations", desc: "Chamfered Wordmark — Warm, elegant brushed rose gold face with dumbbell/plate features.", image: "/logos/option70.png" },
  { id: 71, name: "Iteration 61C: Chamfered Black & Gold Stencil Wordmark", category: "iterations", desc: "Chamfered Wordmark — Matte black letters with a thin gold inner groove running through the center.", image: "/logos/option71.png" },
  { id: 72, name: "Iteration 36.1: Gold & Matte Black Ceramic", category: "iterations", desc: "Diagonal Slice Split — Mirror gold combined with textured matte black ceramic.", image: "/logos/option72.png", isFinalist: true },
  { id: 73, name: "Iteration 36.2: Rose Gold & Charcoal Steel", category: "iterations", desc: "Diagonal Slice Split — Warm rose gold paired with matte dark charcoal steel.", image: "/logos/option73.png", isFinalist: true },
  { id: 74, name: "Iteration 36.3: Platinum & Obsidian", category: "iterations", desc: "Diagonal Slice Split — Polished mirror platinum chrome combined with matte dark obsidian.", image: "/logos/option74.png", isFinalist: true },
  { id: 75, name: "Iteration 36.4: Champagne Gold & Dark Bronze", category: "iterations", desc: "Diagonal Slice Split — Brushed champagne gold paired with sandblasted dark bronze.", image: "/logos/option75.png", isFinalist: true }
];


